name: Update-UPM-Branch

on:
  push:
    tags:
      - v*
  create:

jobs:
  update:
    if: ${{startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag name
        id: tag
        run: echo ::set-output name=name::${GITHUB_REF#refs/tags/v}

      - name: Create UPM branch
        uses: hecomi/create-upm-branch-action@main
        with:
          git-tag: ${{steps.tag.outputs.name}}
          pkg-root-dir-path: Assets/uREPL
          main-branch: master
          root-files: README.md LICENSE.md CHANGELOG.md Third_Party_Notices.md
